interface ServiceItem {
  id: string;
  title: string;
  desc: string;
  image: string;
  description?: string;
  imageType: string;
}

export const services: ServiceItem[] = [
  {
    id: "01/",
    title: "Rennovation",
    desc: "Comprehensive and professional building cleaning solutions...",
    description: "We offer comprehensive professional building cleaning services designed to maintain spotless, hygienic, and welcoming environments for commercial, residential, and industrial properties.",
    image: "/renovation.jpeg",
    imageType: "default",
  },
  {
    id: "02/",
    title: "Electrical Fittings & Fixture Services",
    desc: "From wiring to professional electrical fixture installations...",
    description: "We provide expert electrical fittings and fixture services, ensuring safe, efficient, and reliable electrical systems for residential, commercial, and industrial properties.",
    image: "/Electrical.jpeg",
    imageType: "electrical",
  },
  {
    id: "03/",
    title: "Plumbing & Sanitary Contracting",
    desc: "Our plumbing and sanitary team handles installation and contracting...",
    description: "We provide top-tier plumbing and sanitary contracting services, delivering reliable installation, maintenance, and repair solutions for all types of properties.",
    image: "/Plumber service.jpeg",
    imageType: "plumbing",
  },
  {
    id: "04/",
    title: "Air-Conditioning, Ventilations & Air Filtration Systems Installation & Maintenance",
    desc: "We provide complete air conditioning, ventilation, and filtration services...",
    description: "We provide complete air conditioning, ventilation, and air filtration systems installation and maintenance services, ensuring optimal indoor air quality, comfort, and energy efficiency.",
    image: "/AC repair.jpeg",
    imageType: "fan",
  },
  {
    id: "05/",
    title: "Painting Contracting",
    desc: "Professional interior and exterior painting services...",
    description: "We provide professional painting contracting services, delivering high-quality interior and exterior painting solutions that transform and protect your property.",
    image: "/painting.jpeg",
    imageType: "paint",
  },
  {
    id: "06/",
    title: "Carpentry & Flooring Contracting",
    desc: "Custom carpentry and professional flooring solutions...",
    description: "We offer professional carpentry and flooring contracting services, providing expert craftsmanship and high-quality materials to enhance the beauty, functionality, and value of your space.",
    image: "/carpentry.jpeg",
    imageType: "default",
  },
  {
    id: "07/",
    title: "Concrete Repairs",
    desc: "Fast, durable, and reliable concrete repair services...",
    description: "We offer expert concrete repair services designed to restore the structural integrity, safety, and appearance of deteriorated or damaged concrete structures.",
    image: "/concrete repair.jpeg",
    imageType: "fan",
  },
  {
    id: "08/",
    title: "Floor and Wall Tiling Works",
    desc: "Premium quality floor and wall tile installation and repair...",
    description: "We offer expert floor and wall tiling works, delivering precise installation and flawless finishes for residential, commercial, and industrial spaces.",
    image: "/tile.jpeg",
    imageType: "default",
  },
  {
    id: "09/",
    title: "Metal/Steel Roof Installation",
    desc: "Expert metal and steel roof installation and maintenance...",
    description: "We specialize in metal and steel roof installation, providing durable, weather-resistant, and energy-efficient roofing solutions for residential, commercial, and industrial buildings.",
    image: "/steel roof.jpeg",
    imageType: "roofing",
  },
  {
    id: "10/",
    title: "Strengthening Solutions",
    desc: "Advanced structural strengthening services...",
    description: "We provide advanced structural strengthening solutions designed to restore, enhance, and increase the load-bearing capacity of existing concrete, steel, and masonry structures.",
    image: "/strengthening.jpeg",
    imageType: "default",
  },
  {
    id: "11/",
    title: "Steel Gates",
    desc: "Design, fabrication, and fixing of premium steel gates...",
    description: "We specialize in the design, fabrication, and installation of high-quality steel gates, offering robust security, exceptional durability, and aesthetic appeal for residential, commercial, and industrial properties.",
    image: "/steel gate.jpeg",
    imageType: "default",
  },
  {
    id: "12/",
    title: "Partitions & False Ceilings Contracting",
    desc: "Expert installation of partitions and false ceilings...",
    description: "We provide professional partition and false ceiling contracting services, offering innovative interior solutions that enhance the aesthetics, acoustics, and functionality of any space.",
    image: "/partition.jpeg",
    imageType: "default",
  },
  {
    id: "13/",
    title: "Facilities Management Services",
    desc: "Complete and reliable facilities management support...",
    description: "We offer comprehensive facilities management services designed to ensure the smooth, efficient, and safe operation of your residential, commercial, or industrial properties.",
    image: "/facility.jpeg",
    imageType: "default",
  },
  {
    id: "14/",
    title: "Cladding Works",
    desc: "Professional wall cladding and structural finishing...",
    description: "We specialize in professional cladding works, providing high-quality exterior and interior wall cladding solutions that enhance building aesthetics, insulation, and weather resistance.",
    image: "/Cladding.jpeg",
    imageType: "default",
  },
  {
    id: "15/",
    title: "Sanitary Installation & Piping Repairing",
    desc: "Reliable sanitary setup and piping repair services...",
    description: "We provide professional sanitary installation and piping repair services, ensuring efficient, hygienic, and leak-free water supply and waste management systems for all types of buildings.",
    image: "/sanitary.jpeg",
    imageType: "default",
  },
  {
    id: "16/",
    title: "Bollard Installation",
    desc: "Heavy-duty bollard installation for traffic and security control...",
    description: "We offer professional bollard installation services, providing robust traffic control and perimeter security solutions for commercial, industrial, and public spaces.",
    image: "/bollards.jpeg",
    imageType: "default",
  },
  {
    id: "17/",
    title: "Automatic Rolling Shutters",
    desc: "High-quality automatic rolling shutter and door solutions...",
    description: "We provide high-quality automatic rolling shutter systems for warehouses, shops, factories, and commercial facilities. Our shutters are designed for security, durability, and smooth automated operation.",
    image: "/Shutter door.jpeg",
    imageType: "default",
  },
  {
    id: "18/",
    title: "Crack Injection ( Wet & Dry )",
    desc: "Specialized high-pressure injection solutions for repairing concrete cracks and leaks...",
    description: "We provide professional crack injection services for both wet and dry conditions, utilizing advanced resins to effectively seal cracks, stop leaks, and restore structural integrity.",
    image: "/crack-injection.jpeg",
    imageType: "default",
  },
  {
    id: "19/",
    title: "Automatic Garage Doors",
    desc: "Premium, reliable, and smooth-operating automated garage doors for homes and businesses...",
    description: "We supply and install premium automatic garage doors, offering convenience, enhanced security, and modern aesthetics for residential and commercial properties.",
    image: "/garage-door.jpeg",
    imageType: "default",
  },
  {
    id: "20/",
    title: "Long Range Card Readers",
    desc: "Advanced access control systems offering high-performance long-range detection...",
    description: "We supply and install advanced long-range card readers, providing secure, efficient, and hands-free access control solutions for parking systems, gated communities, and corporate facilities.",
    image: "/card-reader.jpeg",
    imageType: "default",
  },
  {
    id: "21/",
    title: "Gate Automations",
    desc: "Smart and seamless gate automation solutions for residential and industrial complexes...",
    description: "We specialize in gate automation systems, transforming manual gates into smart, secure, and smoothly operated automated access points for residential, commercial, and industrial properties.",
    image: "/gate-automation.jpeg",
    imageType: "default",
  },
  {
    id: "22/",
    title: "Steel Fences",
    desc: "Durable and secure heavy-duty steel fencing fabrication and setup...",
    description: "We design, fabricate, and install high-quality steel fences, providing durable, secure, and visually appealing perimeter protection for residential, commercial, and industrial properties.",
    image: "/steel-fence.jpeg",
    imageType: "default",
  },
  {
    id: "23/",
    title: "Handrail Installation",
    desc: "Professional custom handrail systems designed for ultimate safety and aesthetics...",
    description: "We provide professional handrail installation services, offering high-quality, durable, and stylish handrail systems that enhance safety and aesthetics in residential, commercial, and public spaces.",
    image: "/handrail.jpeg",
    imageType: "default",
  }
];